config/routes.rb
Hacklander::Application.routes.draw do
  resources :diary_entries

end

app/models/diary_entry.rb
class DiaryEntry < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diary_entries_controller.rb
class DiaryEntriesController < ApplicationController
  # GET /diary_entries
  # GET /diary_entries.json
  def index
    @diary_entries = DiaryEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diary_entries }
    end
  end

  # GET /diary_entries/1
  # GET /diary_entries/1.json
  def show
    @diary_entry = DiaryEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diary_entry }
    end
  end

  # GET /diary_entries/new
  # GET /diary_entries/new.json
  def new
    @diary_entry = DiaryEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diary_entry }
    end
  end

  # GET /diary_entries/1/edit
  def edit
    @diary_entry = DiaryEntry.find(params[:id])
  end

  # POST /diary_entries
  # POST /diary_entries.json
  def create
    @diary_entry = DiaryEntry.new(params[:diary_entry])

    respond_to do |format|
      if @diary_entry.save
        format.html { redirect_to @diary_entry, notice: 'Diary entry was successfully created.' }
        format.json { render json: @diary_entry, status: :created, location: @diary_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @diary_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diary_entries/1
  # PUT /diary_entries/1.json
  def update
    @diary_entry = DiaryEntry.find(params[:id])

    respond_to do |format|
      if @diary_entry.update_attributes(params[:diary_entry])
        format.html { redirect_to @diary_entry, notice: 'Diary entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diary_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diary_entries/1
  # DELETE /diary_entries/1.json
  def destroy
    @diary_entry = DiaryEntry.find(params[:id])
    @diary_entry.destroy

    respond_to do |format|
      format.html { redirect_to diary_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diary_entries_helper.rb
module DiaryEntriesHelper
end

app/views/diary_entries/_form.html.erb
<%= form_for(@diary_entry) do |f| %>
  <% if @diary_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary_entry.errors.count, "error") %> prohibited this diary_entry from being saved:</h2>

      <ul>
      <% @diary_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diary_entries/edit.html.erb
<h1>Editing diary_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary_entry %> |
<%= link_to 'Back', diary_entries_path %>

app/views/diary_entries/index.html.erb
<h1>Listing diary_entries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diary_entries.each do |diary_entry| %>
  <tr>
    <td><%= diary_entry.name %></td>
    <td><%= diary_entry.description %></td>
    <td><%= link_to 'Show', diary_entry %></td>
    <td><%= link_to 'Edit', edit_diary_entry_path(diary_entry) %></td>
    <td><%= link_to 'Destroy', diary_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diary entry', new_diary_entry_path %>

app/views/diary_entries/new.html.erb
<h1>New diary_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', diary_entries_path %>

app/views/diary_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @diary_entry.name %>
</p>

<p>
  <b>Description:</b>
  <%= @diary_entry.description %>
</p>


<%= link_to 'Edit', edit_diary_entry_path(@diary_entry) %> |
<%= link_to 'Back', diary_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacklander</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>